[package]
name = "axum-tera-datastar"
version = "0.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
axum-macros = "0.5.1"
datastar = { version = "0.3.1", features = ["axum" ] }
serde = { version = "1.0.229", features = ["derive"] }
tera = { version = "2.1.0", features = ["fast", "glob_fs"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
tower-http = { version = "0.7.0", features = ["fs"] }
